version: "3.5"

services:

  devops-test-app:
   container_name: devops-test-app-nodejs
   depends_on:
     - devops-global-postgres
   build: . 
   command: >
    sh -c "npm run migrate-up &&
           npm run start" 
   tty: true
   ports:
     - 3081:3081

   networks:
     -  proxynet

   volumes:
     - .:/devops-test-app/
     - /devops-test-app/node_modules

  devops-global-postgres:
   hostname: devops-global-postgres
   image: postgres:9.4-alpine
   container_name: devops-test-app-db
   
   environment: 
    - POSTGRES_HOST_AUTH_METHOD=trust

   ports: 
     - 5432:5432

   networks:
     -  proxynet

   volumes: 
     - devops-test-app-db:/var/lib/postgresql/data

volumes: 
    devops-test-app-db:
        
networks:
  proxynet:
    name: devops-test-app