version: "3.5"

services:

  devops-test-app:
   container_name: devops-test-app-nodejs
   build: . 
   command: >
    sh -c "npm run migrate-up &&
           npm run start" 
   tty: true
   ports:
     - 3081:3081
   links:
    - devops-global-postgres

   networks:
     - my-networks

   volumes:
     - .:/devops-test-app/
     - /devops-test-app/node_modules

  devops-global-postgres:
   image: postgres:9.4-alpine
   container_name: devops-test-app-db
   
   environment: 
    - POSTGRES_HOST_AUTH_METHOD=trust
    - HOSTNAME=devops-global-postgres

   ports: 
     - 5432:5432

   networks:
     - my-networks

   volumes: 
     - devops-test-app-db:/var/lib/postgresql/data

volumes: 
    devops-test-app-db:
        
networks:
   my-networks:
    external: true